apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: eso
  namespace: argocd
spec:
  destination:
    namespace: argocd
    server: "https://kubernetes.default.svc"
  project: default
  sources:
    - chart: external-secrets
      repoURL: "https://charts.external-secrets.io/"
      targetRevision: 0.9.6
      helm:
        releaseName: eso
        valueFiles:
        - $kubernetessecrets/apps/eso/values.yaml
    - ref: kubernetessecrets
      repoURL: "https://github.com/XvAbrahamvX/argoprojects.git"
    - repoURL: "https://github.com/XvAbrahamvX/argoprojects.git"
      path: kubernetessecrect/apps/eso/resources 
      targetRevision: main
