apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: eso
  namespace: eso
spec:
  destination:
    namespace: eso
    server: "https://kubernetes.default.svc"
  project: default
  sources:
    - chart: external-secrets
      repoURL: "https://charts.external-secrets.io/"
      targetRevision: 0.9.6
      helm:
        releaseName: eso
        # parameters:
        # - name: "webhook.create"
        #   value: "false"
        # - name: "certController.rbac.create"
        #   value: "false"
        # - name: "rbca.create"
        #   value: "false"
        # - name: "rbca.servicebindings.create"
        #   value: "false"
    - repoURL: "https://github.com/XvAbrahamvX/argoprojects.git"
      path: kubernetessecrect/apps/eso/resources 
      targetRevision: main
