apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: example1
  namespace: eso
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: SecretStore
    name: eso-secret              # name of the SecretStore (or kind specified)
  target:
    name: argocd-secret # name of the k8s Secret to be created
  data:
  - secretKey: 3PbVHhMgE4bmMQRf57k8GaoNYXb+scow307VuhmWl+g=
    remoteRef:
      key: 3PbVHhMgE4bmMQRf57k8GaoNYXb+scow307VuhmWl+g=
      property: tls.crt