apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: example1
  namespace: argocd
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: SecretStore
    name: eso-secret              # name of the SecretStore (or kind specified)
  target:
    name: secret-to-be-created # name of the k8s Secret to be created
  dataFrom:
  - find:
      name:
        # match secret name with regexp
        regexp: "tls-.*"
  - find:
      tags:
        # fetch secrets based on label combination
        app: "nginx"