apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: example1
  namespace: eso
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: SecretStore
    name: secret              # name of the SecretStore (or kind specified)
  target:
    name: secret  # name of the k8s Secret to be created
  data:
  - secretKey: extra
    remoteRef:
      key: secret
      property: extra