apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: example1
  namespace: eso
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: SecretStore
    name: eso-secret              # name of the SecretStore (or kind specified)
  target:
    name: eso-external-secrets-webhook # name of the k8s Secret to be created
  data:
  - secretKey: eso-external-secrets-webhook
    remoteRef:
      key: data
      property: tls.crt