apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: secret
  namespace: eso
spec:
  provider:
    kubernetes:
      remoteNamespace: eso
      auth: 
        serviceAccount:
          name: "eso-external-secrets"
      server:
        # url: "https://myapiserver.tld"
        caProvider:
          type: ConfigMap
          name: kube-root-ca.crt
          key: ca.crt