apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: secrets
  namespace: argocd
spec:
  provider:
    kubernetes:
      remoteNamespace: argocd
      server:
        caProvider:
        type: Secret
        name: eso-external-secrets-webhook
        key: ca.crt
      auth:
        serviceAccount: 
          name: default
        # url: "https://myapiserver.tld"
        # caProvider:
        #   type: ConfigMap
        #   name: kube-root-ca.crt
        #   key: ca.crt