apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: secrets
  namespace: argocd
spec:
  provider:
    kubernetes:
      remoteNamespace: default
      server:
        # url: "https://myapiserver.tld"
        # caProvider:
        #   type: ConfigMap
        #   name: kube-root-ca.crt
        #   key: ca.crt