apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: fake-test-external
  namespace: eso
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: fake-test
    kind: ClusterSecretStore
  target:
    name: secret-to-be-created
  data:
  - secretKey: foo_bar
    remoteRef:
      key: /foo/bar
      version: v1
  dataFrom:
  - extract:
      key: /foo/baz