apiVersion: argoproj.io/v1alpha1
kind: Application
metadata: 
  name: eso-internal
  namespace: argocd
spec: 
  destination: 
    namespace: eso
    server: "https://kubernetes.default.svc"
  project: default
  source: 
    path: main
    repoURL: "https://github.com/XvAbrahamvX/argoprojects/tree/05c8c6fa6a8d8376a961a6eb08d99db4b6e48f9e/secrets"
    targetRevision: master
    helm:
      releaseName: eso
      valueFiles:
        - $secrets/secretstore.yml
        - $secrets/externalstore.yml
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
