apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: credentials-secret
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: SecretStore
    name: k8s-store             # name of the SecretStore (or kind specified)
  target:
    name: credentials-secret  # name of the k8s Secret to be created
  data:
  - secretKey: username
    remoteRef:
      key: credentials-secret
      property: username

  - secretKey: password
    remoteRef:
      key: credentials-secret
      property: password